### ISSUE TITLE
Show CNCF membership level

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#468] opened 2018-03-27 18:56 UTC
Please modify cncf_members.yml to show each member as a nested item of platinum, gold, silver, nonprofit, or academic. Member levels are shown on: https://www.cncf.io/about/members/

In the card, CNCF Member should instead say CNCF Silver Member, with Silver substituted by the appropriate category.

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:24
we miss `apcera`

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:28
not sure about `cloud66` and `cloudfoundry`

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:31
we miss `grafana`

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:33
we miss `kong`

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:33
and we miss `mayadata`

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:34
And `mlab`

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:36
And `shurenyun`

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:40
End user members are duplicate of something else. Not sure how we will handle this stuff.

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:40
we miss `box`

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 18:44
I have these uncategorized items:
`
  - https://www.crunchbase.com/organization/cloud-native-computing-foundation
  - https://www.crunchbase.com/organization/cloudblocks
  - https://www.crunchbase.com/organization/dataman
  - https://www.crunchbase.com/organization/ericsson
  - https://www.crunchbase.com/organization/js-foundation
  - https://www.crunchbase.com/organization/mashape
  - https://www.crunchbase.com/organization/objectlabs
  - https://www.crunchbase.com/organization/open-container-initiative
  - https://www.crunchbase.com/organization/open-vswitch
  - https://www.crunchbase.com/organization/opencontrail
  - https://www.crunchbase.com/organization/openebs
  - https://www.crunchbase.com/organization/opensds
  - https://www.crunchbase.com/organization/raintank
  - https://www.crunchbase.com/organization/the-linux-foundation
  - https://www.crunchbase.com/organization/the-open-api-initiative
`

**Comment by ZeusTheTrueGod** [comment] 2018-03-31 19:48
Regarding filters by cncf relation - should I add nested menu of 'Gold Member', 'Silver Member', and so on? Or keep it just as 'member' in filters and then, in a modal card view, display a membership under the logo ?

**Closed** 2018-04-01 20:15 UTC
Labels: enhancement
