### ISSUE TITLE
(NOT MOVING TO LANDSCAPEAPP) Make the landscape an upstream NPM project

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#1015] opened 2018-12-01 00:19 UTC
And then both the CNCF and LFDL landscapes would be downstream implementations. We should do this sooner rather than later to avoid having to maintain 2 forks.

**Comment by ZeusTheTrueGod** [comment] 2018-12-01 10:30
I want to see how much changes we will make within next 2-4 weeks first to decide what can be put to an npm project.

**Comment by ZeusTheTrueGod** [comment] 2018-12-02 08:49
So far here are basic ideas:
1) we extract all the cncf related properties, website name, etc to the single file, `settings.json`, where we try to keep our project specific information. That would be a title, site name, an update server ip address, etc. No secret keys should be stored there though
2) we create a `LandscapeApp` repo, which is almost identical to the landscape with key properties extracted to the `settings.json`, and I would get rid of a special `sandbox`  projects handling

3) CNCF and LFDL projects: I want to use a solution based on either patching a specific folder in node_modules ( and probably later using an alias to keep webpack happy) , or having a script which copies `src/` and `tools/` to the specific app project,  and may be using a file like `src/Header.js.override.js` which is resolved by default when a `src/Header.js` is required. 

Whatever, it is either a solution based on patches or a solution based on overriding specific files. 
I personally want to research an option with keeping the copy of the base app in a cncf or lfdl repo, it would be updated automatically on `yarn update` and each file will have a first line as `//do not edit this file directly`.

**Comment by dankohn** [comment] 2018-12-02 14:05
Yes, starting with a global settings file sounds like a good idea. I don't
recommend that any files should be copied as part of a yarn upgrade.
Instead, we should use npm overwrite or similar so that a local file is
always loaded before the landscapeapp file, if it exists.

But all the custom text, icons, etc. should be specified in the global
settings file.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment] 2018-12-03 06:56
Ok, so after all the errors and trials, I see this issue:
1) babel-node and webpack,  used for our tools and webapp, are quite unfriendly to symlinks and node_modules and just do not want to compile anything inside the node_modules or soft links pointing to node_modules. I'm researching all the keys, like --preserve-symlinks, and still hope that this solution will finally work.
2) I am checking if yarn-patch could work with our files in a working tree, if I can not make all symlinks working properly

**Comment by ZeusTheTrueGod** [comment] 2018-12-03 08:50
Researching a git submodule together with yarn workspace, because it was designed to solve this or similar issues. babel and node_modules are incompatible in a lot of checks and separate file, not sure if they will ever work properly

**Comment by ZeusTheTrueGod** [comment] 2018-12-03 09:45
Finally, I see there are 2 primary goals at this moment
1) get babel-node working with scripts from a `landscape-app` node_modules folder
2) get  webpack compiling components from a `landscape-app` node_modules folder

I got 1) working with a file not in a node_modules folder, but in a different folder

I'd also like to research if I can inject a list of required modules  and scripts into the `package.json`

**Comment by ZeusTheTrueGod** [comment] 2018-12-04 07:59
There is a great plugin for babel, which I plan to use to give local files a priority over those from a node_module.
https://github.com/tleunen/babel-plugin-module-resolver/blob/HEAD/DOCS.md

**Comment by dankohn** [comment] 2018-12-04 12:08
Great.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by ZeusTheTrueGod** [comment] 2018-12-10 07:04
We need to think again about node_modules: when I make a new version of interactive-landscape via merging a PR to its master or just by manually updating a master branch, all our downstream packages like cncf or lfdl need to run `yarn upgrade`, because by design, yarn locks the package version at the moment of `yarn add` and there is no way to tell yarn that the given package should be always fetched from a latest master.

The alternative approach would be not to use node_modules and to run `git clone` and `yarn install` on every build.

**Comment by ZeusTheTrueGod** [comment] 2018-12-10 07:40
Netlify still has some issues with running a webpack build from the node_modules, I'll have to run it locally on their docker image in order to find what goes wrong.

**Comment by dankohn** [comment] 2018-12-10 12:47
I think you can run yarn upgrade as part of the nightly update server to
have yarn move to the latest build within the specified range.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Closed** 2018-12-19 20:16 UTC
Labels: enhancement
