### ISSUE TITLE
Serverless

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#70] opened 2017-02-03 14:52 UTC
I'd like to create a new box between Languages & Frameworks and Databases called Serverless that would include:

AWS Lambda: No good logo. Need to combine AWS and Lambda logos
Serverless: https://serverless.com/_/src/assets/images/serverless_logo.be2d3b90c0910b8d46efd441c96130ed.png
OpenWhisk: http://openwhisk.org/images/apache-openwhisk.svg
Fission: https://github.com/fission/fission

**Comment by moderation** [comment] 2017-02-03 15:23
Other serverless offerings (not a complete list):
- [Azure Functions](https://azure.microsoft.com/en-us/services/functions/)
- [Google Cloud Functions](https://cloud.google.com/functions/)
- [Iron.io IronFunctions](http://open.iron.io/)
- [Webtask](https://webtask.io/)

**Comment by lennypruss** [comment] 2017-02-03 22:06
A more appropriate place might be in platforms as a separate bucket (because they cut across multiple layers and abstract away that complexity).

**Comment by scottraney** [comment] 2017-02-03 23:54
I think it could go either way.  Lamba is clearly a platform, while others like fission will be built on top of Kubernetes and provide some abstractions.

**Comment by craigbox** [comment] 2017-02-06 21:57
Duplicate of #33.

**Comment by arun-gupta** [comment] 2017-04-09 21:19
Was just thinking about this and would be great to see this added. How can I help?

**Comment by shawnpreissner** [comment] 2017-07-21 01:19
This was achieved in the last version with the Event-based Compute category. Thank you all for your input!

**Closed by shawnpreissner** 2017-07-21 01:19 UTC
